// Mocks generated by Mockito 5.4.6 from annotations
// in imjang_app/test/features/auth/presentation/screens/login_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:imjang_app/features/auth/domain/entities/user_entity.dart'
    as _i4;
import 'package:imjang_app/features/auth/presentation/providers/auth_controller.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAutoDisposeNotifierProviderRef_0<T> extends _i1.SmartFake
    implements _i2.AutoDisposeNotifierProviderRef<T> {
  _FakeAutoDisposeNotifierProviderRef_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeAsyncValue_1<T> extends _i1.SmartFake implements _i2.AsyncValue<T> {
  _FakeAsyncValue_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthControllerNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthControllerNotifier extends _i1.Mock
    implements _i3.AuthControllerNotifier {
  MockAuthControllerNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AutoDisposeNotifierProviderRef<_i2.AsyncValue<_i4.UserEntity?>> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue:
                _FakeAutoDisposeNotifierProviderRef_0<
                  _i2.AsyncValue<_i4.UserEntity?>
                >(this, Invocation.getter(#ref)),
          )
          as _i2.AutoDisposeNotifierProviderRef<
            _i2.AsyncValue<_i4.UserEntity?>
          >);

  @override
  _i2.AsyncValue<_i4.UserEntity?> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAsyncValue_1<_i4.UserEntity?>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.AsyncValue<_i4.UserEntity?>);

  @override
  set state(_i2.AsyncValue<_i4.UserEntity?>? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i2.AsyncValue<_i4.UserEntity?> build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: _FakeAsyncValue_1<_i4.UserEntity?>(
              this,
              Invocation.method(#build, []),
            ),
          )
          as _i2.AsyncValue<_i4.UserEntity?>);

  @override
  _i5.Future<void> signUp({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void listenSelf(
    void Function(
      _i2.AsyncValue<_i4.UserEntity?>?,
      _i2.AsyncValue<_i4.UserEntity?>,
    )?
    listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  bool updateShouldNotify(
    _i2.AsyncValue<_i4.UserEntity?>? previous,
    _i2.AsyncValue<_i4.UserEntity?>? next,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
          )
          as bool);
}
