// Mocks generated by Mockito 5.4.x from annotations
// in imjang_app/test/features/complex/presentation/screens/complex_search_screen_test.dart.
// Run: flutter pub run build_runner build --delete-conflicting-outputs
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

import 'package:mockito/mockito.dart' as _i1;
import 'package:imjang_app/features/public_api/domain/entities/apt_list_item.dart' as _i2;

export 'complex_search_screen_test.dart'
    show ComplexSearchState, ComplexSearchNotifier;

abstract class ComplexSearchNotifier {
  ComplexSearchState build();
  Future<void> search(String query);
  Future<void> registerComplex(_i2.AptListItem item);
}

// Minimal state re-export
class ComplexSearchState {
  final List<_i2.AptListItem> searchResults;
  final bool isLoading;
  final String? error;
  final Set<String> registeredApiCodes;

  const ComplexSearchState({
    this.searchResults = const [],
    this.isLoading = false,
    this.error,
    this.registeredApiCodes = const {},
  });
}

class MockComplexSearchNotifier extends _i1.Mock
    implements ComplexSearchNotifier {
  MockComplexSearchNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  ComplexSearchState build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: const ComplexSearchState(),
          )
          as ComplexSearchState);

  @override
  Future<void> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: Future<void>.value(),
            returnValueForMissingStub: Future<void>.value(),
          )
          as Future<void>);

  @override
  Future<void> registerComplex(_i2.AptListItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#registerComplex, [item]),
            returnValue: Future<void>.value(),
            returnValueForMissingStub: Future<void>.value(),
          )
          as Future<void>);
}
