// Mocks generated by Mockito 5.4.x from annotations
// in imjang_app/test/features/complex/presentation/screens/complex_detail_screen_test.dart.
// Run: flutter pub run build_runner build --delete-conflicting-outputs
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:imjang_app/features/complex/domain/entities/complex_entity.dart' as _i3;
import 'package:imjang_app/features/complex/domain/entities/complex_status.dart' as _i4;

export 'complex_detail_screen_test.dart' show ComplexDetailNotifier;

abstract class ComplexDetailNotifier {
  _i2.AsyncValue<_i3.ComplexEntity?> build();
  Future<void> updateStatus(_i4.ComplexStatus newStatus);
  Future<void> deleteComplex();
}

class MockComplexDetailNotifier extends _i1.Mock
    implements ComplexDetailNotifier {
  MockComplexDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AsyncValue<_i3.ComplexEntity?> build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: const _i2.AsyncData<_i3.ComplexEntity?>(null),
          )
          as _i2.AsyncValue<_i3.ComplexEntity?>);

  @override
  Future<void> updateStatus(_i4.ComplexStatus? newStatus) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [newStatus]),
            returnValue: Future<void>.value(),
            returnValueForMissingStub: Future<void>.value(),
          )
          as Future<void>);

  @override
  Future<void> deleteComplex() =>
      (super.noSuchMethod(
            Invocation.method(#deleteComplex, []),
            returnValue: Future<void>.value(),
            returnValueForMissingStub: Future<void>.value(),
          )
          as Future<void>);
}
